name: Unit-tests

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v1

      # Setup system
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install HFST
        run: sudo apt-get install -y hfst

      # Install poetry and install package dependencies
      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install package deps
        run: poetry install

      # Setup pipenv and run unit tests with pytest
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Run Unit Tests
        run: |
          pipenv run test -v
